services:
  # database:
  #   image: postgres
  #   volumes:
  #     - fantasy_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_USER: root
  redis_db:
    image: redis
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
  backend:
    build: backend
    volumes:
      - ./backend/api:/api
    ports:
      - "8000:8000"
    depends_on:
      - redis_db
  # frontend:
  #   build: frontend
  #   volumes:
  #     - ./frontend/app:/app
  #     - /app/node_modules # anonymous persistent volume
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
volumes:
  node_modules:
  redisdata:
